require("lazy").setup({
	require("plugins/mellow"),
	require("plugins/treesitter"),
	require("plugins/telescope"),
	require("plugins/neo-tree"),
	require("plugins/lsp"),
	require("plugins/cmp"),
	-- require("plugins/which-key"),
	require("plugins/autopairs"),
	require("plugins/conform"),
	require("plugins/debug"),
	require("plugins/roslyn"),
}, {
	ui = {
		icons = vim.g.have_nerd_font and {} or {
			cmd = "⌘",
			config = "🛠",
			event = "📅",
			ft = "📂",
			init = "⚙",
			keys = "🗝",
			plugin = "🔌",
			runtime = "💻",
			require = "🌙",
			source = "📄",
			start = "🚀",
			task = "📌",
			lazy = "💤 ",
		},
	},
})
