require("lazy").setup({
	require("plugins/mellow"),
	require("plugins/treesitter"),
	require("plugins/neotree"),
	require("plugins/transparent"),
	require("plugins/telescope"),
	require("plugins/lsp"),
	require("plugins/cmp"),
})
